# Generated by Django 5.0.7 on 2024-08-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
