# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"P\n\x0e\x41rticleRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"4\n\x0f\x41rticleResponse\x12\x12\n\narticle_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t2A\n\x0b\x42logService\x12\x32\n\rCreateArticle\x12\x0f.ArticleRequest\x1a\x10.ArticleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLEREQUEST']._serialized_start=14
  _globals['_ARTICLEREQUEST']._serialized_end=94
  _globals['_ARTICLERESPONSE']._serialized_start=96
  _globals['_ARTICLERESPONSE']._serialized_end=148
  _globals['_BLOGSERVICE']._serialized_start=150
  _globals['_BLOGSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
